<!-- Start Content Block 1-3 -->
<?php echo $this->renderBlock('homepage/section-feature.phtml'); ?>
<!--// END Content Block 1-3 -->
<!-- Start Content Block 1-4 -->
<?php echo $this->renderBlock('homepage/section-information.phtml'); ?>
<!--// END Content Block 1-4 -->
<?php echo $this->renderBlock('homepage/section-team.phtml'); ?>
<!--// End Team 2-1 -->
<!-- Start Content Block 1-7 -->
<?php echo $this->renderBlock('homepage/section-team.phtml'); ?>
<!-- // End Content Block 1-7 -->
<!-- Start Promo 3 -->
<?php echo $this->renderBlock('homepage/section-promo.phtml'); ?>
<!--// END Promo 3 -->
<!-- Start Contact 2 -->
<?php echo $this->renderBlock('homepage/section-contact.phtml'); ?>
<!--// END Contact 2 -->
<!-- Start Footer 1-1 -->
<?php echo $this->renderBlock('homepage/section-footer.phtml'); ?>
<!--// END Footer 1-1 -->

