<div class="copyright-bar bg-grey">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12 pull-left">
                <div class="social-wrap">
                    <ul class="social social-dark">
                        <li><a href="#"><i class="fa fa-2x fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-2x fa-pinterest"></i></a></li>
                        <li><a href="#"><i class="fa fa-2x fa-dribbble"></i></a></li>
                    </ul><!-- /.social -->
                </div>
            </div>

            <div class="col-md-6 col-xs-12 pull-right">
                <p class="text-right">
                    &copy; Design by MinhTran. All Right Reserved 2016.
                </p>
            </div>
        </div>
    </div>
</div>