<header id="header-3">
    <?php echo $this->renderBlock('layout/menu.phtml'); ?>
    <section class="hero">
        <div class="container">
            <div class="brand">
                <img src="/assets/images/logo.png" class="brand-img img-responsive">
            </div>
            <div class="navicon">
                <a id="nav-toggle" class="nav-slide-btn" href="#"><span></span></a>
            </div>
            <div class="col-md-12 text-center">
                <div class="banner-heading">
                    <span class="lead">IDEAL SOLUTION FOR YOUR BUSINESS</span>
                    <h1>YOUR <span class="blue">CIPHERPOLS</span> DO IT ALL</h1>
                </div>
            </div>
            <div class="col-xs-12 text-center">
                <a href="#" class="btn btn-ghost">More Features</a>
            </div>
        </div>
    </section>
</header>