<nav>
    <div class="container">
        <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
            <nav class="pull">
                <ul class="top-nav">
                    <li><a href="#">Home <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                    <li><a href="#">Features <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                    <li><a href="#">Pages <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                    <li><a href="#">Portfolio <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                    <li><a href="#">Team <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                    <li><a href="#">Contact <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                </ul>
            </nav>
        </div>
    </div><!-- /.container-fluid -->
</nav><!-- /.nav -->