<section class="content-block-nopad bg-black">
    <div class="container footer-1-1">

        <div class="row">
            <div class="col-md-7">

                <div class="logo-footer">
                    <img src="/assets/images/logo_footer.png" class="img-responsive logo-shape">
                    <div class="logo-text">Cipherpols</div>
                </div>

                <div class="">
                    <p class="decscription">
                        The One Piece manga and anime series features an extensive cast of characters created by Eiichiro Oda. The series takes place in a fictional universe where vast numbers of pirates, soldiers, revolutionaries, and other adventurers fight each other, using various superhuman and supernatural abilities.
                    </p>
                </div>
            </div>

            <div class="col-md-5">

                <h4>Contact</h4>

                <ul>
                    <li>
                        <span class="glyphicon glyphicon glyphicon-earphone"></span>
                        <a href="tel:+84838486889">
                            (+84) 8 38486889
                        </a>
                    </li>
                    <li>
                        <span class="glyphicon glyphicon glyphicon-envelope"></span>
                        <a href="mailto:info@cipherpol@gmail.com">
                            info@cipherpol@gmail.com
                        </a>
                    </li>
                    <li>
                        <i class="fa fa-map" aria-hidden="true"></i>
                        123 Hoang Hoa Tham Street -
                        Tan Binh District - HCMC</li>
                    <li>
                        <i class="fa fa-fax" aria-hidden="true"></i>
                        (+84) 8 38486811</li>
                </ul>
            </div>


        </div><!-- /.row -->
    </div><!-- /.container -->
</section>