<section id="content-1-7" class="content-1-7 content-block">

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-center">
                <h1>CLIENTS</h1>
                <p>
                    Our 300+ customers have trusted in our work, don't be hesitate to join our happy customer team. <br />
                    Cipherpol will elevate your business website to the next level.
                </p>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="cients-wrap">
            <div class="row">
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img alt="Client Logo" src="/assets/images/partner-logos/logo-bootstrap.png">
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img alt="Client Logo" src="/assets/images/partner-logos/logo-less.png">
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img alt="Client Logo" src="/assets/images/partner-logos/logo-sass.png">
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img alt="Client Logo" src="/assets/images/partner-logos/logo-yeoman.png">
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img alt="Client Logo" src="/assets/images/partner-logos/logo-bower.png">
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img alt="Client Logo" src="/assets/images/partner-logos/logo-jquery.png">
                </div>
            </div><!--end of row-->
        </div>

    </div><!-- /.container -->

</section>