<section id="content-1-3" class="content-block content-1-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="underlined-title">
                    <h1>FEATURES</h1>
                </div>

                <div class="services-wrapper">
                    <div class="col-md-4">
                        <div class="icon">
                            <img src="/assets/images/icon_professional.png" alt="">
                        </div>
                        <div class="editContent">
                            <h4>Group of Professional</h4>
                        </div>
                        <div class="editContent">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="icon">
                            <img src="/assets/images/icon_digital.png" alt="">
                        </div>
                        <div class="editContent">
                            <h4>Digital Marketing Solution</h4>
                        </div>
                        <div class="editContent">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="icon">
                            <img src="/assets/images/icon_global.png" alt="">
                        </div>
                        <div class="editContent">
                            <h4>Able to Work Globally</h4>
                        </div>
                        <div class="editContent">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>