<!--DOCTYPE html -->
<html>
    <head>
        <?php echo $this->renderBlock('layout/meta.phtml'); ?>
        <?php echo $this->renderBlock('layout/head-link.phtml'); ?>
    </head>
    <body>
        <div id="page" class="page">
            <!-- HEADER 3 -->
            <?php echo $this->renderBlock('layout/header.phtml'); ?>
            <!--// END HEADER 3 -->
            <?php echo $this->renderContent(); ?>
            <!-- Start Footer Copyright Bar -->
            <?php echo $this->renderBlock('layout/footer.phtml'); ?>
            <!--// END Footer Copyright Bar -->
        </div><!-- /#page -->
        <?php echo $this->renderBlock('layout/head-script.phtml'); ?>
    </body>
</html>